# Generated by Django 6.1.1 on 2026-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_fuelstation_delete_testrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
