# Generated by Django 6.1.1 on 2026-09-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_fuelstation_latitude_fuelstation_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="geocode_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
