# Generated by Django 6.1.1 on 2026-09-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0004_fuelstation_geocode_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="geocode_match_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
