# Generated by Django 6.1.1 on 2026-09-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0005_fuelstation_geocode_match_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelstation",
            name="geocode_status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="fuelstation",
            name="rack_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
